# BASH settings

# Put this file in your home directory and rename it to .bash_aliases
# Make sure that your ~/.bashrc and/or ~/.profile files source this
# file.


# A few safety and convenience aliases

alias rm='rm -i'        # ask before removing a file
alias cp='cp -ai'       # ask before copying a file over another file
alias mv='mv -i'        # ask before moving a file in place of another file
alias mkdir='mkdir -p'  # make multiple directories in one command

# OS-specific aliases (try running the uname program on its own):
if [ "`uname`" = Darwin ]; then
  # MacOS-specific stuff
  # The "open" command is like clicking something on the dock.
  # If you just type "emacs", it runs in a terminal, without mouse access.
  alias emacs='open -a Emacs'
elif [ "`uname`" = Linux ]; then
  # Linux-specific stuff
  alias o=xdg-open        # open files with appropriate program
fi


# enable executables in the current directory (no more typing ./)
export PATH=.:$PATH


# Default file creation permissions mask
# This number gets subtracted from 777 for directories and 666 for files
# to determine the permissions for a new file or directory.
umask 2
